name: Compilar Mod John Automático 2026
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixar Natives e Headers (Automático)
        run: |
          # Puxa as bibliotecas necessárias para o mod não ficar com 3KB
          git clone https://github.com base
          cp -r base/include . || true
          sudo apt-get update && sudo apt-get install -y clang lld llvm make gcc-multilib

      - name: Compilar Mod SPRX
        run: make

      - name: Upload do Mod Pronto
        uses: actions/upload-artifact@v4
        with:
          name: Mod_John_RDR2_v132
          path: "*.sprx"
