name: Compilar Mod RDR2 PS4 2026
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Ambiente (Correção de Erro)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld llvm make gcc-multilib g++-multilib

      - name: Compilar SPRX
        run: |
          make clean || true
          make
        env:
          CC: clang
          CXX: clang++

      - name: Upload do Mod Pronto
        uses: actions/upload-artifact@v4
        with:
          name: Mod_John_Final_2026
          path: "*.sprx"
